export const AUTHENTICATE = 'AUTHENTICATE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_INCIDENT_SUCCESS = 'GET_INCIDENT_SUCCESS';
export const GET_INCIDENT_FAIL = 'GET_INCIDENT_FAIL';
